services:
  jwt-generator:
    container_name: giwa-jwt-generator
    image: alpine/openssl
    entrypoint: >
      /bin/sh -c "[ ! -f /shared/jwtsecret.key ] && openssl rand -hex 32 | tr -d '\n' > /shared/jwtsecret.key || exit 0"
    volumes:
      - shared:/shared
    restart: "no"
  execution:
    container_name: giwa-el
    depends_on:
      jwt-generator:
        condition: service_completed_successfully
    build:
      context: .
      dockerfile: ./geth/Dockerfile
      args:
        OPGETH_VERSION: v1.101511.1
    env_file:
      - ${NETWORK_ENV:-.env.sepolia}
    ports:
      - "8545:8545"
      - "8546:8546"
      - "30303:30303"
      - "30303:30303/udp"
    volumes:
      - shared:/shared
      - ${EXECUTION_DATA_DIR:-./execution_data}:/app/data
  consensus:
    container_name: giwa-cl
    depends_on:
      jwt-generator:
        condition: service_completed_successfully
      execution:
        condition: service_started
    build:
      context: .
      dockerfile: ./node/Dockerfile
      args:
        OPNODE_VERSION: v1.13.4
    env_file:
      - ${NETWORK_ENV:-.env.sepolia}
    ports:
      - "9545:9545"
      - "9222:9222"
      - "9222:9222/udp"
      - "7300:7300"
    volumes:
      - shared:/shared

volumes:
  shared:
